apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
  image: {{ image }}
  liveness:
    path: /actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /actuator/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1012Mi
    requests:
      cpu: 250m
      memory: 512Mi
  maskinporten:
    enabled: true
  ingresses:
    - {{ ingress }}
  accessPolicy:
    inbound:
      rules:
      {{#each azureAccessInbound}}
        - application: {{this.application}}
          namespace: {{this.namespace}}
          cluster: {{this.cluster}}
      {{/each}}
  replicas:
    min: 1
    max: 1

