apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
  secureLogs:
    enabled: true
  image: {{ image }}
  liveness:
    path: /actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  env:
    - name: BIDRAG_PERSON_URL
      value: https://{{ azure.person }}
    - name: BIDRAG_PERSON_SCOPE
      value: {{ azure.person_clientid }}

