management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"

springdoc:
  packages-to-scan: no.nav.bidrag.template.controller
spring.main.banner-mode: off
---
spring.config.activate.on-profile: nais,local
