name: Build and deploy
on:
  pull_request:
    types: [ ready_for_review, opened, synchronize ]

jobs:
  build_and_deploy:
    name: "Build and deploy to main"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      nais_variabler_filnavn: main.yaml